# This is a basic workflow to help you get started with Actions

name: Compile Html5 CI

concurrency: 
  group: production
  cancel-in-progress: true

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools --quiet
          haxelib run flixel-tools setup --never
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install newgrounds --quiet
          haxelib install linc_luajit --quiet
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/mastereric/polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install actuate --quiet
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm html5
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml html5 --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: htmlBuild
          path: 'export/release/html5/bin' 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup heroku
        # Pushes the web version of the engine to heroku automatically. Why heroku? No idea leave me alone.
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login 
      - uses: actions/download-artifact@v2
        with:
          name: htmlBuild
          path: build/artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build/artifact
      - name: Deploy to heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: jade-engine
        working-directory: build/artifact
        # Git config since git will obviously ask for it
        run: |
          git config --global init.defaultBranch master
          git init
          git add *
          git config user.email a@a
          git config user.name a
          heroku git:remote -a jade-engine
          git commit -m "Gihub actions commit" --allow-empty
          git branch
          git show-ref
          git push heroku master
      - name: Final destination
        run: |
          echo Your game is up at ${{ secrets.HEROKU_APP_NAME }}.herokuapp.com (Unless you did something stupid)
